blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Documentation
    url: https://xavierarpa.gitbook.io/uniflux
    about: Check out the full documentation
  - name: ğŸ› ï¸ UniFlux Toolkit
    url: https://github.com/xavierarpa/UniFlux.Toolkit
    about: Try the UniFlux Toolkit for additional tools
  - name: â“ Q&A Discussions
    url: https://github.com/xavierarpa/UniFlux/discussions
    about: Ask questions and discuss ideas with the community
